### ISSUE TITLE
Use EncodeUriComponent() to encode users data when used as a URL parameter

### ISSUE THREAD

**Issue by lanzone1** [webminds-inc/clickreport#1]
When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

```javascript
const encodeUriComponent = require('encodeUriComponent');
const url = 'https://service.clickreport.com/wmcaudit.js?id=' + encodeUriComponent(data.clickreport_id);
```

**Comment by webminds-inc** [comment]
Thank you! I've updated my script. Please check again!
