### ISSUE TITLE
Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by lanzone1** [webminds-inc/clickreport#2]
When reviewing your template, we've noticed that `gtmOnSuccess` or `gtmOnFailure` are called incorrectly. This is required so that users can sequence their tags correctly. The current code always calls `gtmOnSuccess`, even on failure:

```javascript
injectScript(url, function() {}, data.gtmOnFailure, url);
data.gtmOnSuccess();
```
Consider something like this:
```javascript
injectScript(url, data.gtmOnSuccess, data.gtmOnFailure, url);
```

**Comment by webminds-inc** [comment]
I've updated my template script. Please review again.
Thank you!
